drop table if exists article CASCADE ;
drop table if exists commande CASCADE ;
drop table if exists destinataire CASCADE ;
drop table if exists produit CASCADE ;
drop sequence hibernate_sequence if exists;
create sequence hibernate_sequence start with 1 increment by 1;
 
    
    create table article (
       id bigint generated by default as identity (start with 1),
        prix numeric(19,2),
        produit_id bigint not null,
        quantite integer check (quantite>=1),
        commande_id bigint not null,
        primary key (id)
    );

    
    create table commande (
       id bigint generated by default as identity (start with 1),
        date_commande timestamp,
        date_livraison timestamp,
        numero_commande varchar(255),
        prix numeric(19,2),
        destinataire_id bigint,
        primary key (id)
    );
    
    create table destinataire (
    	id bigint generated by default as identity (start with 1),
        adresse varchar(255),
        code_postal varchar(255),
        nom varchar(255),
        pays varchar(255),
        ville varchar(255),
        primary key (id)
    ); 

    
    create table produit (
       id bigint generated by default as identity (start with 1),
        description varchar(255) not null,
        nom varchar(255) not null,
        nombre_jour_livraison bigint,
        prix numeric(19,2) not null,
        primary key (id)
    );

    
    alter table article 
       add constraint FKec1alyo24fooaxjmko7k2vmu1 
       foreign key (commande_id) 
       references commande;
    
    alter table commande 
       add constraint FKk37f8h0bevoaxsu6sryk5x2si 
       foreign key (destinataire_id) 
       references destinataire;
       
       
       alter table destinataire add constraint destinataire_unique unique  (adresse, code_postal, nom, pays, ville);