    
    drop table if exists adresse CASCADE; 
    
    drop table if exists article CASCADE; 
    
    drop table if exists commande CASCADE; 
    
    drop table if exists destinataire CASCADE; 
    
    drop table if exists pays CASCADE; 
    
    drop table if exists produit CASCADE; 
    
    drop table if exists ville CASCADE; 
    
    create table adresse (
       id bigint generated by default as identity (start with 1),
        numero_et_rue varchar(255),
        ville_id varchar(255) not null,
        primary key (id)
    ); 
    
    create table article (
       id bigint generated by default as identity (start with 1),
        prix numeric(19,2),
        quantite bigint check (quantite>=1),
        primary key (id)
    ); 
    
    create table commande (
       id bigint generated by default as identity (start with 1),
        date_commande time,
        date_livraison date,
        numero_commande varchar(255),
        prix numeric(19,2) not null,
        destinataire_id bigint,
        primary key (id)
    ); 
    
    create table destinataire (
       id bigint generated by default as identity (start with 1),
        adresse varchar(255),
        code_postal varchar(255),
        email varchar(255),
        nom varchar(255),
        pays varchar(255),
        prenom varchar(255),
        ville varchar(255),
        primary key (id)
    ); 
    
    create table pays (
       code varchar(255) not null,
        continent varchar(255),
        libelle varchar(255),
        primary key (code)
    ); 
    
    create table produit (
       id bigint generated by default as identity (start with 1),
        description varchar(255) not null,
        nom varchar(255) not null,
        nombre_jour_livraison integer,
        prix numeric(19,2) not null,
        primary key (id)
    ); 
    
    create table ville (
       id bigint generated by default as identity (start with 1),
        code_postal varchar(255),
        departement varchar(255),
        nom varchar(255),
        region varchar(255),
        pays_id varchar(255) not null,
        primary key (id)
    ); 
    
    alter table destinataire 
       add constraint UK_email_destinataire unique (email); 
    
    alter table pays 
       add constraint UK_libelle_pays unique (libelle); 
    
    alter table adresse 
       add constraint fk_adresse_ville 
       foreign key (ville_id) 
       references ville; 
    
    alter table commande 
       add constraint fk_commande_destinataire 
       foreign key (destinataire_id) 
       references destinataire; 
    
    alter table ville 
       add constraint fk_ville_pays 
       foreign key (pays_id) 
       references pays;